package noppes.npcs;

import net.minecraft.entity.EnumCreatureAttribute;
import net.minecraft.nbt.NBTTagCompound;
import noppes.npcs.constants.EnumParticleType;
import noppes.npcs.constants.EnumPotionType;

public class DataStats {
   public int attackStrength = 5;
   public int attackSpeed = 20;
   public int attackRange = 2;
   public int knockback = 0;
   public int fireDelay = 20;
   public int delayVariance = 40;
   public int rangedRange = 15;
   public int fireRate = 5;
   public int burstCount = 1;
   public int accuracy = 90;
   public int moveSpeed = 6;
   public int aggroRange = 16;
   public EnumPotionType potionType;
   public int potionDuration;
   public int potionAmp;
   public int maxHealth;
   public int respawnTime;
   public int spawnCycle;
   public boolean hideKilledBody;
   public Resistances resistances;
   protected boolean immuneToFire;
   public boolean canDrown;
   public boolean burnInSun;
   public boolean noFallDamage;
   public boolean healthRegen;
   public int pDamage;
   public int pImpact;
   public int pSize;
   public int pSpeed;
   public int pArea;
   public int pDur;
   public boolean pPhysics;
   public boolean pXlr8;
   public boolean pGlows;
   public boolean pExplode;
   public boolean pRender3D;
   public boolean pSpin;
   public boolean pStick;
   public EnumPotionType pEffect;
   public EnumParticleType pTrail;
   public int pEffAmp;
   public String fireSound;
   public EnumCreatureAttribute creatureType;
   private EntityNPCInterface npc;

   public DataStats(EntityNPCInterface npc) {
      this.potionType = EnumPotionType.None;
      this.potionDuration = 5;
      this.potionAmp = 0;
      this.maxHealth = 20;
      this.respawnTime = 20;
      this.spawnCycle = 0;
      this.hideKilledBody = false;
      this.resistances = new Resistances();
      this.immuneToFire = false;
      this.canDrown = true;
      this.burnInSun = false;
      this.noFallDamage = false;
      this.healthRegen = true;
      this.pDamage = 4;
      this.pImpact = 0;
      this.pSize = 5;
      this.pSpeed = 10;
      this.pArea = 0;
      this.pDur = 5;
      this.pPhysics = true;
      this.pXlr8 = false;
      this.pGlows = false;
      this.pExplode = false;
      this.pRender3D = false;
      this.pSpin = false;
      this.pStick = false;
      this.pEffect = EnumPotionType.None;
      this.pTrail = EnumParticleType.None;
      this.pEffAmp = 0;
      this.fireSound = "random.bow";
      this.creatureType = EnumCreatureAttribute.UNDEFINED;
      this.npc = npc;
   }

   public NBTTagCompound writeToNBT(NBTTagCompound compound) {
      compound.func_74766_a("Resistances", this.resistances.writeToNBT());
      compound.func_74768_a("MaxHealth", this.maxHealth);
      compound.func_74768_a("AggroRange", this.aggroRange);
      compound.func_74757_a("HideBodyWhenKilled", this.hideKilledBody);
      compound.func_74768_a("RespawnTime", this.respawnTime);
      compound.func_74768_a("SpawnCycle", this.spawnCycle);
      compound.func_74768_a("CreatureType", this.creatureType.ordinal());
      compound.func_74768_a("MoveSpeed", this.moveSpeed);
      compound.func_74757_a("HealthRegen", this.healthRegen);
      compound.func_74768_a("AttackStrenght", this.attackStrength);
      compound.func_74768_a("AttackRange", this.attackRange);
      compound.func_74768_a("AttackSpeed", this.attackSpeed);
      compound.func_74768_a("KnockBack", this.knockback);
      compound.func_74768_a("PotionEffect", this.potionType.ordinal());
      compound.func_74768_a("PotionDuration", this.potionDuration);
      compound.func_74768_a("PotionAmp", this.potionAmp);
      compound.func_74768_a("MaxFiringRange", this.rangedRange);
      compound.func_74768_a("FireRate", this.fireRate);
      compound.func_74768_a("FiringDelay", this.fireDelay);
      compound.func_74768_a("DelayVariance", this.delayVariance);
      compound.func_74768_a("BurstCount", this.burstCount);
      compound.func_74768_a("Accuracy", this.accuracy);
      compound.func_74768_a("pDamage", this.pDamage);
      compound.func_74768_a("pImpact", this.pImpact);
      compound.func_74768_a("pSize", this.pSize);
      compound.func_74768_a("pSpeed", this.pSpeed);
      compound.func_74768_a("pArea", this.pArea);
      compound.func_74768_a("pDur", this.pDur);
      compound.func_74757_a("pPhysics", this.pPhysics);
      compound.func_74757_a("pXlr8", this.pXlr8);
      compound.func_74757_a("pGlows", this.pGlows);
      compound.func_74757_a("pExplode", this.pExplode);
      compound.func_74757_a("pRender3D", this.pRender3D);
      compound.func_74757_a("pSpin", this.pSpin);
      compound.func_74757_a("pStick", this.pStick);
      compound.func_74768_a("pEffect", this.pEffect.ordinal());
      compound.func_74768_a("pTrail", this.pTrail.ordinal());
      compound.func_74768_a("pEffAmp", this.pEffAmp);
      compound.func_74778_a("FiringSound", this.fireSound);
      compound.func_74757_a("ImmuneToFire", this.immuneToFire);
      compound.func_74757_a("CanDrown", this.canDrown);
      compound.func_74757_a("BurnInSun", this.burnInSun);
      compound.func_74757_a("NoFallDamage", this.noFallDamage);
      return compound;
   }

   public void readToNBT(NBTTagCompound compound) {
      this.resistances.readToNBT(compound.func_74775_l("Resistances"));
      this.maxHealth = compound.func_74762_e("MaxHealth");
      this.hideKilledBody = compound.func_74767_n("HideBodyWhenKilled");
      this.aggroRange = compound.func_74762_e("AggroRange");
      this.respawnTime = compound.func_74762_e("RespawnTime");
      this.spawnCycle = compound.func_74762_e("SpawnCycle");
      this.creatureType = EnumCreatureAttribute.values()[compound.func_74762_e("CreatureType") % EnumPotionType.values().length];
      this.moveSpeed = compound.func_74762_e("MoveSpeed");
      this.healthRegen = compound.func_74767_n("HealthRegen");
      this.attackStrength = compound.func_74762_e("AttackStrenght");
      this.attackSpeed = compound.func_74762_e("AttackSpeed");
      this.attackRange = compound.func_74762_e("AttackRange");
      this.knockback = compound.func_74762_e("KnockBack");
      this.potionType = EnumPotionType.values()[compound.func_74762_e("PotionEffect") % EnumPotionType.values().length];
      this.potionDuration = compound.func_74762_e("PotionDuration");
      this.potionAmp = compound.func_74762_e("PotionAmp");
      this.rangedRange = compound.func_74762_e("MaxFiringRange");
      this.fireRate = compound.func_74762_e("FireRate");
      this.fireDelay = compound.func_74762_e("FiringDelay");
      this.delayVariance = compound.func_74762_e("DelayVariance");
      this.burstCount = compound.func_74762_e("BurstCount");
      this.accuracy = compound.func_74762_e("Accuracy");
      this.pDamage = compound.func_74762_e("pDamage");
      this.pImpact = compound.func_74762_e("pImpact");
      this.pSize = compound.func_74762_e("pSize");
      this.pSpeed = compound.func_74762_e("pSpeed");
      this.pArea = compound.func_74762_e("pArea");
      this.pDur = compound.func_74762_e("pDur");
      this.pPhysics = compound.func_74767_n("pPhysics");
      this.pXlr8 = compound.func_74767_n("pXlr8");
      this.pGlows = compound.func_74767_n("pGlows");
      this.pExplode = compound.func_74767_n("pExplode");
      this.pRender3D = compound.func_74767_n("pRender3D");
      this.pSpin = compound.func_74767_n("pSpin");
      this.pStick = compound.func_74767_n("pStick");
      this.pEffect = EnumPotionType.values()[compound.func_74762_e("pEffect") % EnumPotionType.values().length];
      this.pTrail = EnumParticleType.values()[compound.func_74762_e("pTrail") % EnumParticleType.values().length];
      this.pEffAmp = compound.func_74762_e("pEffAmp");
      this.fireSound = compound.func_74779_i("FiringSound");
      this.immuneToFire = compound.func_74767_n("ImmuneToFire");
      this.canDrown = compound.func_74767_n("CanDrown");
      this.burnInSun = compound.func_74767_n("BurnInSun");
      this.noFallDamage = compound.func_74767_n("NoFallDamage");
      this.npc.setImmuneToFire(this.immuneToFire);
      this.npc.updateHitbox();
   }
}
